// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_TYPE_ANY     DataType = 0
	DataType_TYPE_LOGPASS DataType = 1
	DataType_TYPE_CARD    DataType = 2
	DataType_TYPE_FILE    DataType = 3
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "TYPE_ANY",
		1: "TYPE_LOGPASS",
		2: "TYPE_CARD",
		3: "TYPE_FILE",
	}
	DataType_value = map[string]int32{
		"TYPE_ANY":     0,
		"TYPE_LOGPASS": 1,
		"TYPE_CARD":    2,
		"TYPE_FILE":    3,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PostCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Valid         string                 `protobuf:"bytes,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCardRequest) Reset() {
	*x = PostCardRequest{}
	mi := &file_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCardRequest) ProtoMessage() {}

func (x *PostCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCardRequest.ProtoReflect.Descriptor instead.
func (*PostCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *PostCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *PostCardRequest) GetValid() string {
	if x != nil {
		return x.Valid
	}
	return ""
}

func (x *PostCardRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PostCardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PostDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowId         uint32                 `protobuf:"varint,1,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	Length        uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDataResponse) Reset() {
	*x = PostDataResponse{}
	mi := &file_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDataResponse) ProtoMessage() {}

func (x *PostDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDataResponse.ProtoReflect.Descriptor instead.
func (*PostDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *PostDataResponse) GetRowId() uint32 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *PostDataResponse) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowId         uint32                 `protobuf:"varint,1,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetDataRequest) GetRowId() uint32 {
	if x != nil {
		return x.RowId
	}
	return 0
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Valid         string                 `protobuf:"bytes,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetCardResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *GetCardResponse) GetValid() string {
	if x != nil {
		return x.Valid
	}
	return ""
}

func (x *GetCardResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PostLogPassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostLogPassRequest) Reset() {
	*x = PostLogPassRequest{}
	mi := &file_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostLogPassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostLogPassRequest) ProtoMessage() {}

func (x *PostLogPassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostLogPassRequest.ProtoReflect.Descriptor instead.
func (*PostLogPassRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *PostLogPassRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PostLogPassRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PostLogPassRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetLogPassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogPassResponse) Reset() {
	*x = GetLogPassResponse{}
	mi := &file_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogPassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogPassResponse) ProtoMessage() {}

func (x *GetLogPassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogPassResponse.ProtoReflect.Descriptor instead.
func (*GetLogPassResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetLogPassResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetLogPassResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PostFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostFileRequest) Reset() {
	*x = PostFileRequest{}
	mi := &file_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostFileRequest) ProtoMessage() {}

func (x *PostFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostFileRequest.ProtoReflect.Descriptor instead.
func (*PostFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *PostFileRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *PostFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PostFileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *GetFileResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetDataInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=api.DataType" json:"data_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataInfoRequest) Reset() {
	*x = GetDataInfoRequest{}
	mi := &file_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataInfoRequest) ProtoMessage() {}

func (x *GetDataInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataInfoRequest.ProtoReflect.Descriptor instead.
func (*GetDataInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetDataInfoRequest) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_TYPE_ANY
}

type DataInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowId         uint32                 `protobuf:"varint,1,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataInfo) Reset() {
	*x = DataInfo{}
	mi := &file_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInfo) ProtoMessage() {}

func (x *DataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInfo.ProtoReflect.Descriptor instead.
func (*DataInfo) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *DataInfo) GetRowId() uint32 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *DataInfo) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *DataInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *DataInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetDataInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserData      []*DataInfo            `protobuf:"bytes,1,rep,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataInfoResponse) Reset() {
	*x = GetDataInfoResponse{}
	mi := &file_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataInfoResponse) ProtoMessage() {}

func (x *GetDataInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataInfoResponse.ProtoReflect.Descriptor instead.
func (*GetDataInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetDataInfoResponse) GetUserData() []*DataInfo {
	if x != nil {
		return x.UserData
	}
	return nil
}

var File_proto_api_proto protoreflect.FileDescriptor

const file_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/api.proto\x12\x03api\"\a\n" +
	"\x05Empty\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"~\n" +
	"\x0fPostCardRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\tR\x05valid\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"A\n" +
	"\x10PostDataResponse\x12\x15\n" +
	"\x06row_id\x18\x01 \x01(\rR\x05rowId\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\"'\n" +
	"\x0eGetDataRequest\x12\x15\n" +
	"\x06row_id\x18\x01 \x01(\rR\x05rowId\"\\\n" +
	"\x0fGetCardResponse\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\tR\x05valid\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"h\n" +
	"\x12PostLogPassRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"F\n" +
	"\x12GetLogPassResponse\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"f\n" +
	"\x0fPostFileRequest\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"D\n" +
	"\x0fGetFileResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"@\n" +
	"\x12GetDataInfoRequest\x12*\n" +
	"\tdata_type\x18\x01 \x01(\x0e2\r.api.DataTypeR\bdataType\"o\n" +
	"\bDataInfo\x12\x15\n" +
	"\x06row_id\x18\x01 \x01(\rR\x05rowId\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\"A\n" +
	"\x13GetDataInfoResponse\x12*\n" +
	"\tuser_data\x18\x01 \x03(\v2\r.api.DataInfoR\buserData*H\n" +
	"\bDataType\x12\f\n" +
	"\bTYPE_ANY\x10\x00\x12\x10\n" +
	"\fTYPE_LOGPASS\x10\x01\x12\r\n" +
	"\tTYPE_CARD\x10\x02\x12\r\n" +
	"\tTYPE_FILE\x10\x032\x96\x04\n" +
	"\x12PassManagerService\x121\n" +
	"\bRegister\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse\x12.\n" +
	"\x05Login\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse\x127\n" +
	"\bPostCard\x12\x14.api.PostCardRequest\x1a\x15.api.PostDataResponse\x124\n" +
	"\aGetCard\x12\x13.api.GetDataRequest\x1a\x14.api.GetCardResponse\x12=\n" +
	"\vPostLogPass\x12\x17.api.PostLogPassRequest\x1a\x15.api.PostDataResponse\x12:\n" +
	"\n" +
	"GetLogPass\x12\x13.api.GetDataRequest\x1a\x17.api.GetLogPassResponse\x129\n" +
	"\bPostFile\x12\x14.api.PostFileRequest\x1a\x15.api.PostDataResponse(\x01\x126\n" +
	"\aGetFile\x12\x13.api.GetDataRequest\x1a\x14.api.GetFileResponse0\x01\x12@\n" +
	"\vGetDataInfo\x12\x17.api.GetDataInfoRequest\x1a\x18.api.GetDataInfoResponseB\vZ\tapi/protob\x06proto3"

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData []byte
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_api_proto_goTypes = []any{
	(DataType)(0),               // 0: api.DataType
	(*Empty)(nil),               // 1: api.Empty
	(*LoginRequest)(nil),        // 2: api.LoginRequest
	(*LoginResponse)(nil),       // 3: api.LoginResponse
	(*PostCardRequest)(nil),     // 4: api.PostCardRequest
	(*PostDataResponse)(nil),    // 5: api.PostDataResponse
	(*GetDataRequest)(nil),      // 6: api.GetDataRequest
	(*GetCardResponse)(nil),     // 7: api.GetCardResponse
	(*PostLogPassRequest)(nil),  // 8: api.PostLogPassRequest
	(*GetLogPassResponse)(nil),  // 9: api.GetLogPassResponse
	(*PostFileRequest)(nil),     // 10: api.PostFileRequest
	(*GetFileResponse)(nil),     // 11: api.GetFileResponse
	(*GetDataInfoRequest)(nil),  // 12: api.GetDataInfoRequest
	(*DataInfo)(nil),            // 13: api.DataInfo
	(*GetDataInfoResponse)(nil), // 14: api.GetDataInfoResponse
}
var file_proto_api_proto_depIdxs = []int32{
	0,  // 0: api.GetDataInfoRequest.data_type:type_name -> api.DataType
	13, // 1: api.GetDataInfoResponse.user_data:type_name -> api.DataInfo
	2,  // 2: api.PassManagerService.Register:input_type -> api.LoginRequest
	2,  // 3: api.PassManagerService.Login:input_type -> api.LoginRequest
	4,  // 4: api.PassManagerService.PostCard:input_type -> api.PostCardRequest
	6,  // 5: api.PassManagerService.GetCard:input_type -> api.GetDataRequest
	8,  // 6: api.PassManagerService.PostLogPass:input_type -> api.PostLogPassRequest
	6,  // 7: api.PassManagerService.GetLogPass:input_type -> api.GetDataRequest
	10, // 8: api.PassManagerService.PostFile:input_type -> api.PostFileRequest
	6,  // 9: api.PassManagerService.GetFile:input_type -> api.GetDataRequest
	12, // 10: api.PassManagerService.GetDataInfo:input_type -> api.GetDataInfoRequest
	3,  // 11: api.PassManagerService.Register:output_type -> api.LoginResponse
	3,  // 12: api.PassManagerService.Login:output_type -> api.LoginResponse
	5,  // 13: api.PassManagerService.PostCard:output_type -> api.PostDataResponse
	7,  // 14: api.PassManagerService.GetCard:output_type -> api.GetCardResponse
	5,  // 15: api.PassManagerService.PostLogPass:output_type -> api.PostDataResponse
	9,  // 16: api.PassManagerService.GetLogPass:output_type -> api.GetLogPassResponse
	5,  // 17: api.PassManagerService.PostFile:output_type -> api.PostDataResponse
	11, // 18: api.PassManagerService.GetFile:output_type -> api.GetFileResponse
	14, // 19: api.PassManagerService.GetDataInfo:output_type -> api.GetDataInfoResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		EnumInfos:         file_proto_api_proto_enumTypes,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
